-- PLAYAPI-REQ-006 / PLAYAPI-NFR-004: banimento + ELO base (v0.3)
ALTER TABLE users
  ADD COLUMN elo_rating INT NOT NULL DEFAULT 1000 AFTER role,
  ADD COLUMN banned_at DATETIME NULL DEFAULT NULL AFTER updated_at,
  ADD COLUMN banned_reason VARCHAR(500) NULL DEFAULT NULL AFTER banned_at;
