#!/usr/bin/env bash
# FragHub SysAdmin Panel — installer
# Deploys fraghub-sysadmin to /opt/fraghub/sysadmin
set -euo pipefail

INSTALL_DIR="${FRAGHUB_SYSADMIN_DIR:-/opt/fraghub/sysadmin}"
SYSADMIN_PORT="${FRAGHUB_SYSADMIN_PORT:-8081}"   # internal Node port
SYSADMIN_PUBLIC_PORT="${FRAGHUB_SYSADMIN_PUBLIC_PORT:-8080}"  # Nginx public port
FRAGHUB_USER="${FRAGHUB_USER:-fraghub}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SOURCE_DIR="${REPO_ROOT}/services/fraghub-sysadmin"

ALLOWED_SERVICES=(fraghub-api mariadb nginx fraghub-cs2 fraghub-csgo fraghub-sysadmin)
ALLOWED_ACTIONS=(start stop restart)

# ── helpers ────────────────────────────────────────────────────────────────────
info()  { echo -e "\033[0;34m[sysadmin-setup]\033[0m $*"; }
ok()    { echo -e "\033[0;32m[sysadmin-setup]\033[0m $*"; }
err()   { echo -e "\033[0;31m[sysadmin-setup]\033[0m $*" >&2; exit 1; }

# ── preflight ──────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || err "Run as root (sudo)"
[[ -d "$SOURCE_DIR" ]] || err "Source dir not found: $SOURCE_DIR"
command -v node >/dev/null 2>&1 || err "Node.js not installed"
command -v npm  >/dev/null 2>&1 || err "npm not installed"
id "$FRAGHUB_USER" >/dev/null 2>&1 || err "User '$FRAGHUB_USER' does not exist"

# ── copy source ────────────────────────────────────────────────────────────────
info "Copying source to $INSTALL_DIR ..."
mkdir -p "$INSTALL_DIR"
rsync -a --exclude=node_modules --exclude=dist "$SOURCE_DIR/" "$INSTALL_DIR/"

# ── read DB credentials from fraghub-api .env ─────────────────────────────────
API_ENV="/opt/fraghub/api/.env"
DB_HOST="127.0.0.1"; DB_PORT="3306"; DB_NAME="fraghub_db"
DB_USER="fraghub_app"; DB_PASSWORD=""

if [[ -f "$API_ENV" ]]; then
  # shellcheck disable=SC1090
  DB_HOST=$(grep -m1 '^DB_HOST=' "$API_ENV" | cut -d= -f2- | tr -d '"' || echo "127.0.0.1")
  DB_PORT=$(grep -m1 '^DB_PORT=' "$API_ENV" | cut -d= -f2- | tr -d '"' || echo "3306")
  DB_NAME=$(grep -m1 '^DB_NAME=' "$API_ENV" | cut -d= -f2- | tr -d '"' || echo "fraghub_db")
  DB_USER=$(grep -m1 '^DB_USER=' "$API_ENV" | cut -d= -f2- | tr -d '"' || echo "fraghub_app")
  DB_PASSWORD=$(grep -m1 '^DB_PASSWORD=' "$API_ENV" | cut -d= -f2- | tr -d '"' || echo "")
fi

# ── write .env ─────────────────────────────────────────────────────────────────
info "Writing .env ..."
cat > "$INSTALL_DIR/.env" <<EOF
PORT=${SYSADMIN_PORT}
NODE_ENV=production
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
FRAGHUB_REPO_ROOT=${REPO_ROOT}
FRAGHUB_STATE_DIR=${FRAGHUB_STATE_DIR:-/opt/fraghub/state}
EOF
chown "root:${FRAGHUB_USER}" "$INSTALL_DIR/.env"
chmod 640 "$INSTALL_DIR/.env"

# ── build ──────────────────────────────────────────────────────────────────────
info "Installing dependencies and building ..."
cd "$INSTALL_DIR"
npm ci --no-audit --no-fund
npm run build

# ── sudoers ────────────────────────────────────────────────────────────────────
info "Writing sudoers rules ..."
SUDOERS_FILE="/etc/sudoers.d/fraghub-sysadmin"

{
  echo "# FragHub SysAdmin — generated by sysadmin-setup.sh"
  echo "# Do not edit manually"
  echo ""
  for svc in "${ALLOWED_SERVICES[@]}"; do
    for act in "${ALLOWED_ACTIONS[@]}"; do
      echo "${FRAGHUB_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl ${act} ${svc}"
    done
  done
  echo ""
  # LinuxGSM update runners
  for game in cs2 csgo; do
    echo "${FRAGHUB_USER} ALL=(${FRAGHUB_USER}) NOPASSWD: /home/${FRAGHUB_USER}/lgsm/${game}server update"
  done
  echo ""
  # Full update pipeline (plugin reinstall)
  echo "${FRAGHUB_USER} ALL=(root) NOPASSWD: /bin/bash ${REPO_ROOT}/scripts/plugin-update-cs2.sh"
} > "$SUDOERS_FILE"
chmod 440 "$SUDOERS_FILE"
visudo -c -f "$SUDOERS_FILE" || { rm -f "$SUDOERS_FILE"; err "sudoers syntax error"; }

# ── systemd unit ───────────────────────────────────────────────────────────────
info "Installing systemd service ..."
cat > /etc/systemd/system/fraghub-sysadmin.service <<EOF
[Unit]
Description=FragHub SysAdmin Panel
After=network.target mariadb.service
Wants=mariadb.service

[Service]
Type=simple
User=${FRAGHUB_USER}
Group=${FRAGHUB_USER}
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=${INSTALL_DIR}/.env
ExecStart=/usr/bin/node dist/server/index.js
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable fraghub-sysadmin
systemctl restart fraghub-sysadmin

# ── nginx LAN block ────────────────────────────────────────────────────────────
NGINX_CONF="/etc/nginx/sites-available/fraghub-sysadmin"
if command -v nginx >/dev/null 2>&1; then
  info "Writing Nginx config (LAN-only, public port ${SYSADMIN_PUBLIC_PORT} → internal ${SYSADMIN_PORT}) ..."
  # Use quoted heredoc delimiter so nginx vars ($host etc.) are NOT bash-expanded
  cat > "$NGINX_CONF" <<'NGINX_EOF_MARKER'
server {
    listen __PUBLIC_PORT__;
    server_name _;

    # LAN-only access
    allow 10.0.0.0/8;
    allow 172.16.0.0/12;
    allow 192.168.0.0/16;
    allow 127.0.0.1;
    deny all;

    access_log /var/log/fraghub/sysadmin-access.log;
    error_log  /var/log/fraghub/sysadmin-error.log;

    location / {
        proxy_pass         http://127.0.0.1:__INTERNAL_PORT__;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering    off;
        proxy_cache        off;
        client_header_buffer_size    4k;
        large_client_header_buffers  4 16k;
    }
}
NGINX_EOF_MARKER
  sed -i "s/__PUBLIC_PORT__/${SYSADMIN_PUBLIC_PORT}/g; s/__INTERNAL_PORT__/${SYSADMIN_PORT}/g" "$NGINX_CONF"
  ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/fraghub-sysadmin
  nginx -t && systemctl reload nginx
fi

# ── firewall ───────────────────────────────────────────────────────────────────
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q "Status: active"; then
  info "Opening UFW port ${SYSADMIN_PUBLIC_PORT}/tcp ..."
  ufw allow "${SYSADMIN_PUBLIC_PORT}/tcp" comment "fraghub-sysadmin LAN" >/dev/null
fi

# ── health check ───────────────────────────────────────────────────────────────
info "Waiting for service to start ..."
for i in $(seq 1 15); do
  if curl -sf "http://127.0.0.1:${SYSADMIN_PORT}/health" >/dev/null 2>&1; then
    ok "FragHub SysAdmin running: internal http://127.0.0.1:${SYSADMIN_PORT} | LAN http://<server-ip>:${SYSADMIN_PUBLIC_PORT}"
    exit 0
  fi
  sleep 1
done

err "Service did not start in time. Check: journalctl -u fraghub-sysadmin -n 30"
