CREATE TABLE IF NOT EXISTS sb_admins (
  aid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user VARCHAR(64) NOT NULL,
  authid VARCHAR(32) NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (aid),
  UNIQUE KEY uq_sb_admins_authid (authid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sb_bans (
  bid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  authid VARCHAR(32) NOT NULL,
  ip VARCHAR(64) NOT NULL DEFAULT '',
  name VARCHAR(128) NOT NULL DEFAULT '',
  reason VARCHAR(255) NOT NULL DEFAULT '',
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ends DATETIME DEFAULT NULL,
  PRIMARY KEY (bid),
  KEY idx_sb_bans_authid (authid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
