CREATE TABLE IF NOT EXISTS rankme (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  steam VARCHAR(32) NOT NULL,
  name VARCHAR(128) NOT NULL,
  kills INT NOT NULL DEFAULT 0,
  deaths INT NOT NULL DEFAULT 0,
  assists INT NOT NULL DEFAULT 0,
  points INT NOT NULL DEFAULT 0,
  rounds_tr INT NOT NULL DEFAULT 0,
  rounds_ct INT NOT NULL DEFAULT 0,
  lastconnect DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rankme_steam (steam)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
