CREATE TABLE IF NOT EXISTS wk_player_skins (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  steam_id VARCHAR(32) NOT NULL,
  weapon VARCHAR(64) NOT NULL,
  skin_id INT NOT NULL,
  wear FLOAT NOT NULL DEFAULT 0.0001,
  stattrak INT NOT NULL DEFAULT 0,
  nametag VARCHAR(64) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_wk_player_skins_steam_id (steam_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
