CREATE TABLE IF NOT EXISTS sa_admins (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  steam_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  immunity INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_sa_admins_steam_id (steam_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sa_bans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  steam_id BIGINT UNSIGNED NOT NULL,
  reason VARCHAR(255) NOT NULL,
  issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_sa_bans_steam_id (steam_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
